name: halkmarket_ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  persistent_bottom_nav_bar_v2: ^5.3.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  flutter_localizations:
     sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
      - assets/icons/
      - assets/images/
      - assets/images/products/
      - assets/lang/ru.json
      - assets/lang/tr.json
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans.ttf
